name: 'Submodule Notify Parent'

on:
  push:
    branches:
      - main    

jobs:
  notify:
    name: 'Submodule Notify Parent'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.CI_TOKEN }}

    # Update references
    - name: Git Sumbodule Update
      run: |
        git config --global user.email dhkim@imsmobility.co.kr
        git config --global user.name "imsKDH"
        git pull --recurse-submodules
        git submodule update --remote --recursive
        cd ./sub_module
        git push origin HEAD:main
        

    # upload submodule
    - name: Git Sumbodule upload file
      run: |
        cp openapi.json ./sub_module/.
        cd ./sub_module
        git add .
        git commit -m "update openapi.json"
        git push origin main
